title:              "COMMA"
tagline:            "NEXT COMMA NEW THING"
email:              " hvv01829@naver.com"
description:        "디지털 마케터와 PM에 관심있는 블로거 COMMA 입니다 :)"
author:             "Gujuhyun"
baseurl:            "/"
url:                "https://ofcomma.com"
locale:             "ko_KR"
thumbnail:          "/img/hd.jpg"

# Social Profilesb
#twitter_username:   twitter_username
#instagram_username: instagram_username
#facebook_username:  facebook_username
#linkedin_username:  linkedin_username
# 블로그 disqus shortname
disqus:
  shortname: comma-1

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
